### PR TITLE
Use SDL2 for rcore_psp.c

### PR DESCRIPTION
**Pull request by BrownNPC**
Native raylib gamepad functions are now working, and performance is a little bit better.

### CODE REVIEW

**Comment by BrownNPC** [comment]
Alright theres a problem with this. you cannot load textures bigger than 2mb because its loading the texture into Vram, this is my guess. I will check if we can use the gl specific code for rendering but use SDL2 for controls and stuff.

**Comment by BrownNPC** [comment]
mind checking this out @psxdev

**Comment by psxdev** [comment]
Wrong branch. I only check raylib4Consoles branch, this is only to sync with raylib mainstream. platform/rcore_psp.c is only for gl implementation i am not going to maintain sdl code on it. Changes are too much disruptive

**Comment by BrownNPC** [comment]
Actually, it is the raylib4consoles branch

And as far as maintaining sdl code goes. The code is from
platform_desktop_sdl.c, I just modified the build system to link sdl, and
copied the Custom logger function from your gl implementation.

Perhaps a separate file, something like rcore_psp_sdl.c would be better.
Although it would be nice to have the sdl implementation as the default as
it's more complete.

**Comment by psxdev** [comment]
I believe that the aproach would be one of these:
1)  a separate platform file rcore_psp_sdl.c and a new PLATFORM_PSP_SDL. This can be a pain in the ass because there are still some PLATFORM_PSP on some raylib stuff in src directory check searching it  because not all is in recore_xxxx, so maintain that define that is not mainstream give us more pain.

2) maintain changes per platform in rcore_desktop_sdl. Here the pain are two sync with rcore_desktop_sdl.c changes from mainstream that will not know about console defines(no console code on raylib maistream. This is a requirement) and figure out how to use defines per console platform when you are using PLATFORM_DESKTOP_SDL

3) PLATFORM_CONSOLE_SDL if other consoles want to use sdl definitiion  and maintain a new recore_console_sdl.c. Same pain in the ass with how figure out defines per console platform.

All 3 options will need work to do outside recore_xxxx and of course in Makefile. Perhaps the 1) option would be better. All will need maintain new defines outside rcore_xxxx platform file and Makefile

 I will not incorporate broken issues to native console gl platforms. Requirement is always the same:
 native gl platform for consoles should build fine without sdl stuff. We can't put an sdl requirements for consoles using native gl custom platform ( PLATFORM_PROSPERO,  PLATFORM_ORBIS,
PLATFORM_VITA,
PLATFORM_PSP,
PLATFORM_DREAMCAST,
PLATFORM_NINTENDO64 )

**Comment by BrownNPC** [comment]
its okay, i understand. I will maintain a seperate fork then.

**Pull request closed without merging**
